In [1]:
import pandas as pd
import numpy as np

### 1. 데이터 불러오기

In [2]:
train_data = pd.read_csv('data/cs-training.csv')
test_data = pd.read_csv('data/cs-test.csv')

test_data.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0
1,2,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0
2,3,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0
3,4,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0
4,5,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0

### 2. Data info()
- SeriousDlqin2yrs : 2년간 90일까지 기한 경과(연체) 경험 유무
-

In [11]:
test_data.SeriousDlqin2yrs

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
25       NaN
26       NaN
27       NaN
28       NaN
29       NaN
          ..
101473   NaN
101474   NaN
101475   NaN
101476   NaN
101477   NaN
101478   NaN
101479   NaN
101480   NaN
101481   NaN
101482   NaN
101483   NaN
101484   NaN
101485   NaN
101486   NaN
101487   NaN
101488   NaN
101489   NaN
101490   NaN
101491   NaN
101492   NaN
101493   NaN
101494   NaN
101495   NaN
101496   NaN
101497   NaN
101498   NaN
101499   NaN
101500   NaN
101501   NaN
101502   NaN
Name: SeriousDlqin2yrs, Length: 101503, dtype: float64

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
Unnamed: 0                              150000 non-null int64
SeriousDlqin2yrs                        150000 non-null int64
RevolvingUtilizationOfUnsecuredLines    150000 non-null float64
age                                     150000 non-null int64
NumberOfTime30-59DaysPastDueNotWorse    150000 non-null int64
DebtRatio                               150000 non-null float64
MonthlyIncome                           120269 non-null float64
NumberOfOpenCreditLinesAndLoans         150000 non-null int64
NumberOfTimes90DaysLate                 150000 non-null int64
NumberRealEstateLoansOrLines            150000 non-null int64
NumberOfTime60-89DaysPastDueNotWorse    150000 non-null int64
NumberOfDependents                      146076 non-null float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB